on:
    push:
    pull_request:
jobs:
    test_schedule:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                fetch-depth: 0
            - name: Last git commit before a merge
              run: git --no-pager log --reflog
            - name: Last git commit before a merge
              run: git log HEAD@{1} -1