on:
    push:
    pull_request:
jobs:
    test_schedule:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                fetch-depth: 0
            - name: Extract branch name
              shell: bash
              run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
              id: extract_branch
            - name: Dump GitHub context
              env:
                GITHUB_CONTEXT: ${{ toJSON(github) }}
              run: echo "$GITHUB_CONTEXT"
            - name: Git Last commit 2
              run: |
                  echo BASE_REF: $BASE_REF
                  echo BASE_SHA: $BASE_SHA
                  echo EVENT_REF: $EVENT_REF
                  echo EVENT_BEFORE: $EVENT_BEFORE
              env:
                BASE_REF: ${{ github.event.pull_request.base.ref }}
                BASE_SHA: ${{ github.event.pull_request.base.sha }}
                EVENT_REF: ${{ github.event.base_ref }}
                EVENT_BEFORE: ${{ github.event.before }}
            - name: Last git commit before a merge
              run: |
                git fetch
                echo ${BRANCH}
                git rev-list --ancestry-path ${BRANCH}..origin/main | tail -1
                git rev-list --ancestry-path ${{ steps.extract_branch.outputs.branch }}..origin/main | tail -1
                LAST_COMMIT=$(git rev-list --ancestry-path ${BRANCH}..origin/main | tail -1) >> $GITHUB_OUTPUT
              id: last_commit
              env:
                BRANCH: ${{ steps.extract_branch.outputs.branch }}
            - name: Show Last git commit before a merge
              run: |
                echo ${LAST_COMMIT}
                git log ${LAST_COMMIT}
              env:
                LAST_COMMIT: ${{ steps.last_commit.outputs.LAST_COMMIT }}              
            - name: Last git commit before a merge
              run: git log HEAD@{1} -1
              if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true      
            - name: Get all commit
              run: git --no-pager log --reflog       