on:
    push:
    pull_request:
jobs:
    test_schedule:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                fetch-depth: 0
            - name: Git Last commit 1 
              run: git --no-pager log --reflog
            - name: Git Last commit 2
              run: |
                echo ${{ github.event.pull_request.base.ref }}
                echo ${{ github.event.pull_request.base.sha }}
                echo ${{ github.event.base_ref }}
                echo ${{ github.event.before }}
            - name: Last git commit before a merge
              run: git log HEAD@{1} -1
              if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true             