on:
    push:
    pull_request:
jobs:
    test_schedule:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                fetch-depth: 0
            - name: Git Last commit 1 
              run: git --no-pager log --reflog
            - name: Git Last commit 2
              run: |
                  echo BASE_REF: $BASE_REF
                  echo BASE_SHA: $BASE_SHA
                  echo EVENT_REF: $EVENT_REF
                  echo EVENT_BEFORE: $EVENT_BEFORE
              env:
                BASE_REF: ${{ github.event.pull_request.base.ref }}
                BASE_SHA: echo ${{ github.event.pull_request.base.sha }}
                EVENT_REF: echo ${{ github.event.base_ref }}
                EVENT_BEFORE: echo ${{ github.event.before }}
            - name: Last git commit before a merge
              run: git log HEAD@{1} -1
              if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true             