on:
    push:
      branches:
        - main
    pull_request:
jobs:
    test_schedule:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                fetch-depth: 0
            - name: Extract branch name
              shell: bash
              run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
              id: extract_branch
            - name: Dump GitHub context
              env:
                GITHUB_CONTEXT: ${{ toJSON(github) }}
              run: echo "$GITHUB_CONTEXT"
            - name: Last commit HEAD minus one
              run: | 
                #git log --name-status HEAD^..HEAD
                echo "#######################################################"
                git log --name-status HEAD
                echo "#######################################################"
                git log --name-status HEAD^
                echo "#######################################################"
            - name: show refs
              run: git show-ref
            - name: 
              run: |
                git rev-parse --short HEAD
                echo "---------------------------------"
                git rev-parse --short HEAD^